command sbatch --export=PATH
option name=* --job-name $0

default time=24:00:00
option time=* --time $0

default mem=2g --nodes=1 --ntasks-per-node=1
option mem=* --mem=$0
option num_nodes=* --nodes $0
option num_threads=* --cpus-per-task $0

default gpu=0
option gpu=0 -p cpu --account=bbjs-delta-cpu
option gpu=* --account=bbjs-delta-gpu --partition=gpuA40x4 --nodes=1 --ntasks-per-node=1 --gres=gpu:a40:$0 --cpus-per-task=16 --mem=30g --gpu-bind=closest --constraint=scratch
